//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prac4LINQ.LINQDatabaseServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/Prac4LINQ")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Prac4LINQ.LINQDatabaseServiceReference.Appointment[] AppointmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string insuranceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int phoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Prac4LINQ.LINQDatabaseServiceReference.Appointment[] Appointments {
            get {
                return this.AppointmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AppointmentsField, value) != true)) {
                    this.AppointmentsField = value;
                    this.RaisePropertyChanged("Appointments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string insuranceNo {
            get {
                return this.insuranceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.insuranceNoField, value) != true)) {
                    this.insuranceNoField = value;
                    this.RaisePropertyChanged("insuranceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((this.phoneNumberField.Equals(value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Appointment", Namespace="http://schemas.datacontract.org/2004/07/Prac4LINQ")]
    [System.SerializableAttribute()]
    public partial class Appointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Prac4LINQ.LINQDatabaseServiceReference.Doctor DoctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Prac4LINQ.LINQDatabaseServiceReference.Patient PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clinicnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime datetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string insuranceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string registrationNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Prac4LINQ.LINQDatabaseServiceReference.Doctor Doctor {
            get {
                return this.DoctorField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorField, value) != true)) {
                    this.DoctorField = value;
                    this.RaisePropertyChanged("Doctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Prac4LINQ.LINQDatabaseServiceReference.Patient Patient {
            get {
                return this.PatientField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientField, value) != true)) {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clinicname {
            get {
                return this.clinicnameField;
            }
            set {
                if ((object.ReferenceEquals(this.clinicnameField, value) != true)) {
                    this.clinicnameField = value;
                    this.RaisePropertyChanged("clinicname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime datetime {
            get {
                return this.datetimeField;
            }
            set {
                if ((this.datetimeField.Equals(value) != true)) {
                    this.datetimeField = value;
                    this.RaisePropertyChanged("datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string insuranceNo {
            get {
                return this.insuranceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.insuranceNoField, value) != true)) {
                    this.insuranceNoField = value;
                    this.RaisePropertyChanged("insuranceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string registrationNo {
            get {
                return this.registrationNoField;
            }
            set {
                if ((object.ReferenceEquals(this.registrationNoField, value) != true)) {
                    this.registrationNoField = value;
                    this.RaisePropertyChanged("registrationNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doctor", Namespace="http://schemas.datacontract.org/2004/07/Prac4LINQ")]
    [System.SerializableAttribute()]
    public partial class Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Prac4LINQ.LINQDatabaseServiceReference.Appointment[] AppointmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string professionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string registrationNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Prac4LINQ.LINQDatabaseServiceReference.Appointment[] Appointments {
            get {
                return this.AppointmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AppointmentsField, value) != true)) {
                    this.AppointmentsField = value;
                    this.RaisePropertyChanged("Appointments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((this.phoneNumberField.Equals(value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profession {
            get {
                return this.professionField;
            }
            set {
                if ((object.ReferenceEquals(this.professionField, value) != true)) {
                    this.professionField = value;
                    this.RaisePropertyChanged("profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string registrationNo {
            get {
                return this.registrationNoField;
            }
            set {
                if ((object.ReferenceEquals(this.registrationNoField, value) != true)) {
                    this.registrationNoField = value;
                    this.RaisePropertyChanged("registrationNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LINQDatabaseServiceReference.ILINQDatabaseService")]
    public interface ILINQDatabaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/PatientRegistration", ReplyAction="http://tempuri.org/ILINQDatabaseService/PatientRegistrationResponse")]
        bool PatientRegistration(Prac4LINQ.LINQDatabaseServiceReference.Patient p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/DoctorRegistration", ReplyAction="http://tempuri.org/ILINQDatabaseService/DoctorRegistrationResponse")]
        bool DoctorRegistration(Prac4LINQ.LINQDatabaseServiceReference.Doctor d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/GetPatientInfo", ReplyAction="http://tempuri.org/ILINQDatabaseService/GetPatientInfoResponse")]
        Prac4LINQ.LINQDatabaseServiceReference.Patient GetPatientInfo(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/GetDoctorInfo", ReplyAction="http://tempuri.org/ILINQDatabaseService/GetDoctorInfoResponse")]
        Prac4LINQ.LINQDatabaseServiceReference.Doctor GetDoctorInfo(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/AppointmentBooking", ReplyAction="http://tempuri.org/ILINQDatabaseService/AppointmentBookingResponse")]
        bool AppointmentBooking(string pfirstName, string plastName, string dfirstName, string dlastName, System.DateTime appoitmentDateAndTime, string clinicName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/GetAppointment", ReplyAction="http://tempuri.org/ILINQDatabaseService/GetAppointmentResponse")]
        Prac4LINQ.LINQDatabaseServiceReference.Appointment GetAppointment(string pfirstName, string plastName, string dfirstName, string dlastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/AppointmentReschedule", ReplyAction="http://tempuri.org/ILINQDatabaseService/AppointmentRescheduleResponse")]
        bool AppointmentReschedule(string pfirstName, string plastName, string dfirstName, string dlastName, System.DateTime newAppointmentTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILINQDatabaseServiceChannel : Prac4LINQ.LINQDatabaseServiceReference.ILINQDatabaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LINQDatabaseServiceClient : System.ServiceModel.ClientBase<Prac4LINQ.LINQDatabaseServiceReference.ILINQDatabaseService>, Prac4LINQ.LINQDatabaseServiceReference.ILINQDatabaseService {
        
        public LINQDatabaseServiceClient() {
        }
        
        public LINQDatabaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LINQDatabaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LINQDatabaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LINQDatabaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PatientRegistration(Prac4LINQ.LINQDatabaseServiceReference.Patient p) {
            return base.Channel.PatientRegistration(p);
        }
        
        public bool DoctorRegistration(Prac4LINQ.LINQDatabaseServiceReference.Doctor d) {
            return base.Channel.DoctorRegistration(d);
        }
        
        public Prac4LINQ.LINQDatabaseServiceReference.Patient GetPatientInfo(string firstName, string lastName) {
            return base.Channel.GetPatientInfo(firstName, lastName);
        }
        
        public Prac4LINQ.LINQDatabaseServiceReference.Doctor GetDoctorInfo(string firstName, string lastName) {
            return base.Channel.GetDoctorInfo(firstName, lastName);
        }
        
        public bool AppointmentBooking(string pfirstName, string plastName, string dfirstName, string dlastName, System.DateTime appoitmentDateAndTime, string clinicName) {
            return base.Channel.AppointmentBooking(pfirstName, plastName, dfirstName, dlastName, appoitmentDateAndTime, clinicName);
        }
        
        public Prac4LINQ.LINQDatabaseServiceReference.Appointment GetAppointment(string pfirstName, string plastName, string dfirstName, string dlastName) {
            return base.Channel.GetAppointment(pfirstName, plastName, dfirstName, dlastName);
        }
        
        public bool AppointmentReschedule(string pfirstName, string plastName, string dfirstName, string dlastName, System.DateTime newAppointmentTime) {
            return base.Channel.AppointmentReschedule(pfirstName, plastName, dfirstName, dlastName, newAppointmentTime);
        }
    }
}
