<?xml version="1.0" encoding="utf-8"?><Database Name="prac4" Class="ClinicalDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\prac4.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="prac4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="insuranceNo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phoneNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Patient_Appointment" Member="Appointments" ThisKey="insuranceNo" OtherKey="insuranceNo" Type="Appointment" />
    </Type>
  </Table>
  <Table Name="dbo.Doctor" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="registrationNo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="profession" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phoneNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Doctor_Appointment" Member="Appointments" ThisKey="registrationNo" OtherKey="registrationNo" Type="Appointment" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="insuranceNo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="registrationNo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="clinicname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Doctor_Appointment" Member="Doctor" ThisKey="registrationNo" OtherKey="registrationNo" Type="Doctor" IsForeignKey="true" />
      <Association Name="Patient_Appointment" Member="Patient" ThisKey="insuranceNo" OtherKey="insuranceNo" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
</Database>